server:
  port: 8091


##swagger
swagger:
  package: org.dows.license.rest
  host: 127.0.0.1:8090
  title: License服务端
  version: V1.0.0
  description: API接口文档
  license: License
  licenseUrl: http://127.0.0.1:8090/
  contact:
    name: lait
    url: http://127.0.0.1:8090/
    email: lait.zhang@gmail.com

logging:
  level:
    org.dows.license: debug






