#License相关配置
dows:
  license:
    subject: dows_license
    publicAlias: publicCert
    storePass: public_dows1234
    licensePath: E:/temps/dows/license.lic #如果不填默认在用户目录
    #publicKeysStorePath: E:/temps/dows/publicCerts.keystore #不如不填默认需要在resources下放置该文件
